import { AccountTitle, JournalEntry, TaxCategory, TransactionType } from "../types";

export const initialEntries: JournalEntry[] = [
    {
        id: "2025-04-01-001",
        transactionType: TransactionType.INCOME,
        occurrenceDate: "2025-04-01",
        debitAccount: AccountTitle.ACCOUNTS_RECEIVABLE,
        debitAmount: 110000,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.SALES,
        creditAmount: 110000,
        creditTax: TaxCategory.TAXABLE_10,
        client: "株式会社アルファ",
        paymentDate: "2025-05-31",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "Webサイト制作費用（請求書No. A-1001）",
    },
    {
        id: "2025-04-02-001",
        transactionType: TransactionType.EXPENSE,
        occurrenceDate: "2025-04-02",
        debitAccount: AccountTitle.SUPPLIES,
        debitAmount: 3300,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.CASH,
        creditAmount: 3300,
        creditTax: TaxCategory.TAXABLE_10,
        client: "文具店グリーン",
        paymentDate: "2025-04-02",
        paymentAccount: AccountTitle.CASH,
        summary: "ノート・ペン等の購入",
    },
    {
        id: "2025-04-03-001",
        transactionType: TransactionType.EXPENSE,
        occurrenceDate: "2025-04-03",
        debitAccount: AccountTitle.COMMUNICATION,
        debitAmount: 5500,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.BANK_ACCOUNT,
        creditAmount: 5500,
        creditTax: TaxCategory.TAXABLE_10,
        client: "通信キャリアX",
        paymentDate: "2025-04-27",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "4月分モバイル回線料金",
    },
    {
        id: "2025-04-04-001",
        transactionType: TransactionType.EXPENSE,
        occurrenceDate: "2025-04-04",
        debitAccount: AccountTitle.ADVERTISING,
        debitAmount: 22000,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.BANK_ACCOUNT,
        creditAmount: 22000,
        creditTax: TaxCategory.TAXABLE_10,
        client: "リスティング広告サービスY",
        paymentDate: "2025-04-04",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "広告出稿（4月前半）",
    },
    {
        id: "2025-04-05-001",
        transactionType: TransactionType.INCOME,
        occurrenceDate: "2025-04-05",
        debitAccount: AccountTitle.ACCOUNTS_RECEIVABLE,
        debitAmount: 33000,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.SALES,
        creditAmount: 33000,
        creditTax: TaxCategory.TAXABLE_10,
        client: "Beta LLC",
        paymentDate: "2025-05-10",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "保守サポート契約 4月分",
    },
    {
        id: "2025-04-06-001",
        transactionType: TransactionType.EXPENSE,
        occurrenceDate: "2025-04-06",
        debitAccount: AccountTitle.UTILITIES,
        debitAmount: 8800,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.BANK_ACCOUNT,
        creditAmount: 8800,
        creditTax: TaxCategory.TAXABLE_10,
        client: "電力会社Z",
        paymentDate: "2025-04-26",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "3月分電気料金",
    },
    {
        id: "2025-04-07-001",
        transactionType: TransactionType.EXPENSE,
        occurrenceDate: "2025-04-07",
        debitAccount: AccountTitle.RENT,
        debitAmount: 110000,
        debitTax: TaxCategory.NON_TAXABLE,
        creditAccount: AccountTitle.BANK_ACCOUNT,
        creditAmount: 110000,
        creditTax: TaxCategory.NON_TAXABLE,
        client: "不動産管理会社Q",
        paymentDate: "2025-04-07",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "4月分オフィス賃料",
    },
    {
        id: "2025-04-08-001",
        transactionType: TransactionType.INCOME,
        occurrenceDate: "2025-04-08",
        debitAccount: AccountTitle.BANK_ACCOUNT,
        debitAmount: 110000,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.ACCOUNTS_RECEIVABLE,
        creditAmount: 110000,
        creditTax: TaxCategory.TAXABLE_10,
        client: "株式会社アルファ",
        paymentDate: "2025-04-08",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "請求A-1001の入金",
    },
    {
        id: "2025-04-09-001",
        transactionType: TransactionType.EXPENSE,
        occurrenceDate: "2025-04-09",
        debitAccount: AccountTitle.SUPPLIES,
        debitAmount: 12100,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.BANK_ACCOUNT,
        creditAmount: 12100,
        creditTax: TaxCategory.TAXABLE_10,
        client: "ECショップR",
        paymentDate: "2025-04-09",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "プリンター用トナー購入",
    },
    {
        id: "2025-04-10-001",
        transactionType: TransactionType.INCOME,
        occurrenceDate: "2025-04-10",
        debitAccount: AccountTitle.BANK_ACCOUNT,
        debitAmount: 33000,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.ACCOUNTS_RECEIVABLE,
        creditAmount: 33000,
        creditTax: TaxCategory.TAXABLE_10,
        client: "Beta LLC",
        paymentDate: "2025-04-10",
        paymentAccount: AccountTitle.BANK_ACCOUNT,
        summary: "保守4月分の入金",
    },
    {
        id: "2025-04-11-001",
        transactionType: TransactionType.EXPENSE,
        occurrenceDate: "2025-04-11",
        debitAccount: AccountTitle.COMMUNICATION,
        debitAmount: 1650,
        debitTax: TaxCategory.TAXABLE_10,
        creditAccount: AccountTitle.CASH,
        creditAmount: 1650,
        creditTax: TaxCategory.TAXABLE_10,
        client: "コワーキングスペースWi-Fi",
        paymentDate: "2025-04-11",
        paymentAccount: AccountTitle.CASH,
        summary: "ドロップイン利用 Wi-Fi",
    },
];